apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
  namespace: default
  labels:
    app: nginx-demo
spec:
  type: LoadBalancer
  selector:
    app: nginx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
